add md-tutorial
RICORA/alg-wiki pull request #17
Opened 2022-04-30 15:06 UTC by sou1118

Markdown の解説記事を書きました．よろしくお願いします．

2022-04-30 15:53 UTC, phnyo commented on md-tutorial/md1.md
> +```
ここの```がいらないはず

2022-04-30 15:55 UTC, phnyo commented on md-tutorial/md1.md
> +$\left(\bigcap_{i=1}^\infty\bigcup_{j=i}^\infty A_j\right)=0$
ここプラグインがバグったので一行あけてほしいです

2022-04-30 15:56 UTC, phnyo commented on md-tutorial/md1.md
> +```
ここも一行あけてほしいです

2022-04-30 15:58 UTC, phnyo commented on md-tutorial/md1.md
> +空の行で間を開ければ良い．
行の後ろにスペースx2でもできなかったっけ（うろ覚えなので確かめてほしい）

2022-04-30 15:58 UTC, phnyo commented on md-tutorial/md1.md
> +-  覚えやすい記述方式である．
スペース気になるかも

2022-04-30 16:01 UTC, phnyo requested changes
まずは書いていただいてありがとうございました！

大雑把に気になった点をコメントで残してあるのと、ドットとコンマを句点と読点に変えていただければいいかなと思います。

2022-04-30 16:19 UTC, sou1118 commented on md-tutorial/md1.md
> +```
ここの```がないと下の ## リンク までソースコードと判定されてしまいました。

2022-04-30 16:49 UTC, phnyo commented on md-tutorial/md1.md
> +```
バックスラッシュを```の後ろに置くとちゃんとコメン卜アウト的な感じになるっぽいので
\``` を ```\ に修正お願いします

2022-04-30 16:51 UTC, phnyo requested changes
手元のhonkitだとコードブロックの解釈が割とバグるのでコードブロックの前後に空行を入れていただけると嬉しいです

2022-05-01 00:09 UTC, sou1118 commented on md-tutorial/md1.md
> +```
了解です。

2022-05-01 00:32 UTC, sou1118 commented on md-tutorial/md1.md
> +```
インテンドで対処できました。

2022-05-01 00:34 UTC, phnyo commented on md-tutorial/md1.md
> +```
ちょっとあとになっちゃうんですが確認します！

2022-05-01 00:42 UTC, sou1118 commented on md-tutorial/md1.md
> +```
お願いします。

2022-05-01 05:28 UTC, phnyo approved these changes
OK

2022-05-01 05:28 UTC, merged